### ISSUE TITLE
Why does the plugin require Android minSdkVersion 24

### ISSUE THREAD

**Issue by mortenthansen** [xmany/nfc_info#6]
Thanks for sharing this plugin. I have a question though.

Why does the plugin require Android minSdkVersion of 24 when the Android docs mentions API level 16 as the last one where NFC functionality was added?

https://developer.android.com/guide/topics/connectivity/nfc/nfc#create-records

**Comment by xmany** [comment]
Hi, sorry for the late reply, the plugin does not actually require 24, it was written that way simply because of being consistent with my other projects.
